services:
  post-db:
    hostname: post-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "pepsi1234!"
      ACCEPT_EULA: "Y"

  account-db:
    hostname: account-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "pepsi1234!"
      ACCEPT_EULA: "Y"
    
  account-service:
    build:
      context: .
      dockerfile: AccountService/Debug.Dockerfile
    ports:
      - "8081:8080"
    environment:
      ASDBConnectionString: "Server=account-db;Initial Catalog=ASDB;User ID=sa;Password=pepsi1234!;TrustServerCertificate=True;"
    
  post-service:
    build:
      context: .
      dockerfile: PostsService/Debug.Dockerfile
    ports:
      - "8082:8080"
    environment:
      PSDBConnectionString: "Server=post-db;Initial Catalog=PSDB;User ID=sa;Password=pepsi1234!;TrustServerCertificate=True;"
  
  timeline-service:
    build:
      context: .
      dockerfile: TimelineService/Debug.Dockerfile
    ports:
      - "8083:8080"
    environment:
      ASDBConnectionString: "Server=account-db;Initial Catalog=ASDB;User ID=sa;Password=pepsi1234!;TrustServerCertificate=True;"
      PSDBConnectionString: "Server=post-db;Initial Catalog=PSDB;User ID=sa;Password=pepsi1234!;TrustServerCertificate=True;"      
      
  gatewayapi:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: GatewayAPI/Debug.Dockerfile
    depends_on:
      account-service:
        condition: service_started
      post-service:
        condition: service_started
      timeline-service:
        condition: service_started