services:
  post-db:
    hostname: post-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "pepsi1234!"
      ACCEPT_EULA: "Y"
    volumes:
      - post-db:/var/opt/mssql

  account-db:
    hostname: account-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "pepsi1234!"
      ACCEPT_EULA: "Y"
    volumes:
      - account-db:/var/opt/mssql
  
  account-service:
    
  post-service:
  
  timeline-service:

volumes:
  account-db:
  post-db: