services:
  post-db:
    hostname: post-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "pepsi1234!"
      ACCEPT_EULA: "Y"

  account-db:
    hostname: account-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "pepsi1234!"
      ACCEPT_EULA: "Y"
    
  account-service:
    build:
      context: .
      dockerfile: AccountService/Dockerfile
    environment:
      ASDBConnectionString: "Server=account-db;Initial Catalog=ASDB;User ID=sa;Password=pepsi1234!;TrustServerCertificate=True;"
    
  post-service:
    build:
      context: .
      dockerfile: PostsService/Dockerfile
    environment:
      PSDBConnectionString: "Server=post-db;Initial Catalog=PSDB;User ID=sa;Password=pepsi1234!;TrustServerCertificate=True;"
  
  timeline-service:
    build:
      context: .
      dockerfile: TimelineService/Dockerfile
    environment:
      ASDBConnectionString: "Server=account-db;Initial Catalog=ASDB;User ID=sa;Password=pepsi1234!;TrustServerCertificate=True;"
      PSDBConnectionString: "Server=post-db;Initial Catalog=PSDB;User ID=sa;Password=pepsi1234!;TrustServerCertificate=True;"      
      
  gatewayapi:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: GatewayAPI/Dockerfile