services:
  post-db:
    hostname: post-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "pepsi1234!"
      ACCEPT_EULA: "Y"

  account-db:
    hostname: account-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "pepsi1234!"
      ACCEPT_EULA: "Y"
    
  account-service:
    build:
      context: .
      dockerfile: AccountService/Dockerfile
    
  post-service:
    build:
      context: .
      dockerfile: PostsService/Dockerfile
  
  timeline-service:
    build:
      context: .
      dockerfile: TimelineService/Dockerfile
      
  gatewayapi:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: GatewayAPI/Dockerfile