apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault.hcl: |
    ui = true
    storage "file" {
      path = "/vault/data"
    }
    api_addr = "http://127.0.0.1:8200"
    dev {
      dev_root_token_id = "my-token"
    }
    controller {
      api_rate_limit_disable = true
    }