apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: twitter-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: teslatorben/account-service
          ports:
            - containerPort: 8080
          env:
            - name: RAW_SECRET
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: sa-password
            - name: ASDBConnectionString
              value: "Server=accountdb;Initial Catalog=ASDB;User ID=sa;Password=$(RAW_SECRET);TrustServerCertificate=True;"
            - name: VAULT_URL
              value: "http://vault.vault.svc.cluster.local:8200"
            - name: VAULT_TOKEN
              value: "my-token"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: twitter-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: teslatorben/post-service
          ports:
            - containerPort: 8080
          env:
            - name: RAW_SECRET
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: sa-password
            - name: PSDBConnectionString
              value: "Server=postdb;Initial Catalog=PSDB;User ID=sa;Password=$(RAW_SECRET);TrustServerCertificate=True;"
            - name: VAULT_URL
              value: "http://vault.vault.svc.cluster.local:8200"
            - name: VAULT_TOKEN
              value: "my-token"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeline-service
  namespace: twitter-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timeline-service
  template:
    metadata:
      labels:
        app: timeline-service
    spec:
      containers:
        - name: timeline-service
          image: teslatorben/timeline-service
          ports:
            - containerPort: 8080
          env:
            - name: RAW_SECRET
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: sa-password
            - name: ASDBConnectionString
              value: "Server=accountdb;Initial Catalog=ASDB;User ID=sa;Password=$(RAW_SECRET);TrustServerCertificate=True;"
            - name: PSDBConnectionString
              value: "Server=postdb;Initial Catalog=PSDB;User ID=sa;Password=$(RAW_SECRET);TrustServerCertificate=True;"
            - name: VAULT_URL
              value: "http://vault.vault.svc.cluster.local:8200"
            - name: VAULT_TOKEN
              value: "my-token"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayapi
  namespace: twitter-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gatewayapi
  template:
    metadata:
      labels:
        app: gatewayapi
    spec:
      containers:
        - name: gatewayapi
          image: teslatorben/gatewayapi
          ports:
            - containerPort: 8080
          env:
          - name: TimelineServiceUrl
            value: "http://timeline-service:8080/"
          - name: PostServiceUrl
            value: "http://post-service:8080/"
          - name: AccountServiceUrl
            value: "http://account-service:8080/"
          - name: VAULT_URL
            value: "http://vault.vault.svc.cluster.local:8200"
          - name: VAULT_TOKEN
            value: "my-token"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:latest
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          args:
            - "server"
            - "-dev"
            - "-dev-root-token-id=my-token"
          env:
            - name: VAULT_LOCAL_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: vault.hcl
            - name: VAULT_TOKEN
              value: "my-token"
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "my-token"
            - name: VAULT_RATE_LIMIT
              value: "50"
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: data
              mountPath: /vault/data
              readOnly: false
            - name: config
              mountPath: /vault/config
              readOnly: false
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          emptyDir: {}
            
          #configMap:
          #  name: vault-config
