apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: twitter-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: teslatorben/account-service
          ports:
            - containerPort: 8080
          env:
            - name: RAW_SECRET
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: sa-password
            - name: ASDBConnectionString
              value: "Server=accountdb;Initial Catalog=ASDB;User ID=sa;Password=$(RAW_SECRET);TrustServerCertificate=True;"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: twitter-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: teslatorben/post-service
          ports:
            - containerPort: 8080
          env:
            - name: RAW_SECRET
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: sa-password
            - name: PSDBConnectionString
              value: "Server=postdb;Initial Catalog=PSDB;User ID=sa;Password=$(RAW_SECRET);TrustServerCertificate=True;"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeline-service
  namespace: twitter-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timeline-service
  template:
    metadata:
      labels:
        app: timeline-service
    spec:
      containers:
        - name: timeline-service
          image: teslatorben/timeline-service
          ports:
            - containerPort: 8080
          env:
          - name: RAW_SECRET
            valueFrom:
              secretKeyRef:
                name: db-password-secret
                key: sa-password
          - name: ASDBConnectionString
            value: "Server=accountdb;Initial Catalog=ASDB;User ID=sa;Password=$(RAW_SECRET);TrustServerCertificate=True;"
          - name: PSDBConnectionString
            value: "Server=postdb;Initial Catalog=PSDB;User ID=sa;Password=$(RAW_SECRET);TrustServerCertificate=True;"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayapi
  namespace: twitter-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gatewayapi
  template:
    metadata:
      labels:
        app: gatewayapi
    spec:
      containers:
        - name: gatewayapi
          image: teslatorben/gatewayapi
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:latest
          env:
            - name: VAULT_LOCAL_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: vault.hcl
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: data
              mountPath: /vault/data
            - name: config
              mountPath: /vault/config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: vault-config
         