apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accountdb-pvc
  namespace: twitter-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postdb-pvc
  namespace: twitter-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi